<?php

/**
 * @file
 * Provides a plugin system to import demo content.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function demo_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'demo_content.import':
      $output = '';
      $output .= '<p>' . t('This page shows all available demo content extensions.') . '</p>';
      $output .= '<p>' . t('To import content from an extension, select the content and click on import.') . '</p>';
      $output .= '<p>' . t('Remember to clear the cache when updating the info files.') . '</p>';
      return $output;
      break;
  }
}

/**
 * Implements hook_modules_installed().
 */
function demo_content_modules_installed($modules) {
  foreach ($modules as $module) {
    if (!\Drupal::isConfigSyncing()) {
      \Drupal::service('demo_content.manager')->importFromExtension($module);
    }
  }
}

/**
 * Implements hook_themes_installed().
 */
function demo_content_themes_installed($theme_list) {
  foreach ($theme_list as $theme) {
    if (!\Drupal::isConfigSyncing()) {
      \Drupal::service('demo_content.manager')->importFromExtension($theme);
    }
  }
}
